### PR TITLE
Update Organizers.md

### PR DESCRIPTION
**Pull request by JuanCaicedo**
:(

### CODE REVIEW

**Comment by robbiethegeek** [comment]
Not sure this is necessary...

**Comment by robbiethegeek** [comment]
@danpaz @joshfinnie thoughts?

**Comment by JuanCaicedo** [comment]
Personally I think it's weird when I see people on organizers lists and they're not really involved. However if you guys want to keep me on there, I guess I don't mind

**Comment by danpaz** [comment]
:( :( 

I'm ok either way, I understand not wanting to be a phantom organizer. Another idea is making a "Past Organizers" section.

**Comment by joshfinnie** [comment]
uhh, RIP in pieces... ;-)

I like the "Past Organizers" section, but again, not sure this is necessary.

**Comment by JuanCaicedo** [comment]
Updated!

**Pull request merged**
